### ISSUE TITLE
FONT_PRINT

### ISSUE THREAD

**Issue by madhavanatmel** [liyanboy74/glcd-st7920-lib#1]
void GLCD_Font_Print(uint8_t x,uint8_t y,char * String);

 GLCD_Font_Print(3, 4, "HELLO"); this is not printing anything on display ?
 so i have added the inside the  `

//Print Fonted String x=0-15 y=0-7
void GLCD_Font_Print(uint8_t x,uint8_t y,char * String)
{
	int i;
	while(*String)
	{
		for(i=0;i<8;i++)
			GLCD_Buf[i+(x*8)+(y*128)]=Font[(*String)*8+i];
		String++;
		x++;
		if(x>15)
		{
			x=0;
			y++;
		}
      ST7920_SendData(GLCD_Buf);
	}
}`  now printing xxxx on (0,0 - x,y) location . even if try to change the x,y location nothing is happening should i pass some other value to display before sending these value . request you to help me for font adding and changes  in this code

**Comment by liyanboy74** [comment]
Try `void ST7920_GraphicMode (int enable);`  Or `void ST7920_Update(void);`

GLCD_Font_Print(3, 4, `&`"HELLO");

**Comment by madhavanatmel** [comment]
thanks boss...it's working now . sorry interrupt you again which Font Creator have used . i try use some new font but nothing is not working . just suggest me the font creator or font available header link. current font is ok but i need to increase little

**Comment by liyanboy74** [comment]
look at [font.h](https://raw.githubusercontent.com/liyanboy74/glcd-st7920-lib/main/font.h) file.
font is 8*8byte
https://www.min.at/prinz/o/software/pixelfont/
